### ISSUE TITLE
Expose as clojure.spec.alpha

### ISSUE THREAD

**Issue by l3nz** [borkdude/spartan.spec#13]
As spartan.spec is a kind of drop.in replacement for current spec, if it was possible to expose it under the clojure.spec.alpha namespace (maybe through a separate library or something) it would be possible to run things that rely on spec directly on bb.

I came across this problem in https://github.com/l3nz/cli-matic/issues/113 and I think that it would be a nice fit for bb.

**Comment by borkdude** [comment]
@l3nz This library is intended to be used with babashka as a library:

```
export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {spartan.spec {:git/url "https://github.com/borkdude/spartan.spec" :sha "ff7317d67ec15f188afb856d37090e5c9509374e"}}}')
```

If you want to make it compatible with JVM Clojure you can use a reader conditional:

```
$ rlwrap bb
Babashka v0.1.1-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require #?(:bb '[spartan.spec :as s] :clj '[clojure.spec.alpha :as s]))
nil
user=> (s/def ::x int?)
:user/x
```

**Comment by borkdude** [comment]
Eventually I want to include spec into babashka itself, but not right now because it's a moving target.

**Comment by l3nz** [comment]
Thanks I'll try that.

**Comment by borkdude** [comment]
@l3nz I now exposed clojure.spec.alpha when loading `spartan.spec` and cli-matic appears to work now:

https://github.com/borkdude/spartan.spec/blob/master/examples/cli_matic.clj

**Comment by borkdude** [comment]
@l3nz Oh btw, I needed to make this workaround:

```
(ns java.text)
(defrecord SimpleDateFormat [])
```

to fool bb into thinking that the`SimpleDateFormat` class exists. Date conversions in bb are done using the `java.time` API.

**Comment by l3nz** [comment]
Super! I moved a reference to https://github.com/l3nz/cli-matic/issues/113 so I can start playing around :)
